apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project-todo
  template:
    metadata:
      labels:
        app: project-todo
    spec:
      containers:
        - name: project-todo
          image: nidnogg/project-todo:1.04